// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function IsServerRunning():Promise<boolean>;

export function StartServer(arg1:number):Promise<void>;

export function StopServer():Promise<void>;
