// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AcceptTransfer(arg1) {
  return window['go']['app']['App']['AcceptTransfer'](arg1);
}

export function ConfirmRegistration() {
  return window['go']['app']['App']['ConfirmRegistration']();
}

export function CreatePassword(arg1) {
  return window['go']['app']['App']['CreatePassword'](arg1);
}

export function GetFilesInFolder(arg1) {
  return window['go']['app']['App']['GetFilesInFolder'](arg1);
}

export function GetLocalIPs() {
  return window['go']['app']['App']['GetLocalIPs']();
}

export function GetServerPIN() {
  return window['go']['app']['App']['GetServerPIN']();
}

export function GetStoredFiles() {
  return window['go']['app']['App']['GetStoredFiles']();
}

export function GetStoredFolders() {
  return window['go']['app']['App']['GetStoredFolders']();
}

export function IsFirstTimeSetup() {
  return window['go']['app']['App']['IsFirstTimeSetup']();
}

export function IsServerRunning() {
  return window['go']['app']['App']['IsServerRunning']();
}

export function OpenFileByID(arg1) {
  return window['go']['app']['App']['OpenFileByID'](arg1);
}

export function RegisterWithDevice(arg1, arg2, arg3) {
  return window['go']['app']['App']['RegisterWithDevice'](arg1, arg2, arg3);
}

export function RejectRegistration() {
  return window['go']['app']['App']['RejectRegistration']();
}

export function RejectTransfer(arg1) {
  return window['go']['app']['App']['RejectTransfer'](arg1);
}

export function SendTestFile(arg1, arg2, arg3) {
  return window['go']['app']['App']['SendTestFile'](arg1, arg2, arg3);
}

export function Shutdown(arg1) {
  return window['go']['app']['App']['Shutdown'](arg1);
}

export function StartServer(arg1) {
  return window['go']['app']['App']['StartServer'](arg1);
}

export function StopServer() {
  return window['go']['app']['App']['StopServer']();
}

export function VerifyPassword(arg1) {
  return window['go']['app']['App']['VerifyPassword'](arg1);
}
