// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {context} from '../models';

export function CreatePassword(arg1:string):Promise<void>;

export function GetLocalIPs():Promise<Array<string>>;

export function IsFirstTimeSetup():Promise<boolean>;

export function IsServerRunning():Promise<boolean>;

export function RegisterWithDevice(arg1:string,arg2:number):Promise<void>;

export function SendTestFile(arg1:string,arg2:number,arg3:string):Promise<void>;

export function Shutdown(arg1:context.Context):Promise<void>;

export function StartServer(arg1:number):Promise<void>;

export function StopServer():Promise<void>;

export function VerifyPassword(arg1:string):Promise<void>;
