// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {filestore} from '../models';
import {context} from '../models';

export function AcceptTransfer(arg1:string):Promise<void>;

export function ConfirmRegistration():Promise<void>;

export function CreatePassword(arg1:string):Promise<void>;

export function GetLocalIPs():Promise<Array<string>>;

export function GetServerPIN():Promise<string>;

export function GetStoredFiles():Promise<Array<filestore.FileInfo>>;

export function IsFirstTimeSetup():Promise<boolean>;

export function IsServerRunning():Promise<boolean>;

export function OpenFileByID(arg1:number):Promise<void>;

export function RegisterWithDevice(arg1:string,arg2:number,arg3:string):Promise<void>;

export function RejectRegistration():Promise<void>;

export function RejectTransfer(arg1:string):Promise<void>;

export function SendTestFile(arg1:string,arg2:number,arg3:string):Promise<void>;

export function Shutdown(arg1:context.Context):Promise<void>;

export function StartServer(arg1:number):Promise<void>;

export function StopServer():Promise<void>;

export function VerifyPassword(arg1:string):Promise<void>;
